export type Category = 'general' | 'historia' | 'futbol' | 'musica' | 'deportes' | 'peliculas' | 'flora' | 'arte';

export interface Question {
	q: string;
	a: string;
}

export const QUESTIONS: Record<Category, Question[]> = {
	general: [
		{ q: '¿Cuál es la capital de Francia?', a: 'París' },
		{ q: '¿Cuántos continentes hay?', a: 'Siete' },
		{ q: '¿Cuál es el planeta más grande del sistema solar?', a: 'Júpiter' },
		{ q: '¿Cuál es el río más largo del mundo?', a: 'El Nilo' },
		{ q: '¿Cuántos años tiene la Tierra aproximadamente?', a: '4.5 mil millones' },
		{ q: '¿Cuál es el país más grande del mundo?', a: 'Rusia' },
		{ q: '¿En qué año se envió el primer mensaje por ARPANET?', a: '1969' },
		{ q: '¿Cuántos océanos hay?', a: 'Cinco' },
		{ q: '¿Quién es uno de los poetas más famosos de España?', a: 'Federico García Lorca' },
		{ q: '¿Cuál es uno de los elementos sintéticos más caros?', a: 'Californio' },
	],
	historia: [
		{ q: '¿En qué año cayó el Muro de Berlín?', a: '1989' },
		{ q: '¿En qué país se originó el feudalismo europeo?', a: 'Francia' },
		{ q: '¿Quién fue el primer emperador de Roma?', a: 'Octavio Augusto' },
		{ q: '¿En qué año terminó la Segunda Guerra Mundial?', a: '1945' },
		{ q: '¿Quién pintó la Mona Lisa?', a: 'Leonardo da Vinci' },
		{ q: '¿En qué año llegó Colón a América?', a: '1492' },
		{ q: '¿Quién fue Napoleón Bonaparte?', a: 'Emperador de Francia' },
		{ q: '¿En qué año se firmó la Declaración de Independencia de EE.UU.?', a: '1776' },
		{ q: '¿Quién fue el primer presidente de Chile?', a: 'Manuel Blanco Encalada' },
		{ q: '¿En qué año comenzó la Revolución Francesa?', a: '1789' },
	],
	futbol: [
		{ q: '¿Cuántas copas del mundo ha ganado Brasil?', a: 'Cinco' },
		{ q: '¿Cuál es el equipo con más títulos de Champions League?', a: 'Real Madrid' },
		{ q: '¿En qué país se juega el Superclásico entre Boca Juniors y River Plate?', a: 'Argentina' },
		{ q: '¿Cuántos jugadores hay en un equipo de fútbol en el campo?', a: 'Once' },
		{ q: '¿Quién es el máximo goleador histórico de la selección argentina?', a: 'Lionel Messi' },
		{ q: '¿En qué año ganó Argentina la Copa del Mundo por tercera vez?', a: '2022' },
		{ q: '¿Cuántos campeonatos mundiales ha ganado Alemania?', a: 'Cuatro' },
		{ q: '¿Quién ganó el Balón de Oro 2023?', a: 'Lionel Messi' },
		{ q: '¿Cuál es el estadio con mayor capacidad de América Latina?', a: 'Estadio Monumental (Argentina)' },
		{ q: '¿En qué zona del campo juega un portero?', a: 'En la portería' },
	],
	musica: [
		{ q: '¿Cuántos integrantes tenían los Beatles?', a: 'Cuatro' },
		{ q: '¿Qué instrumento de viento prehistórico se considera de los más antiguos?', a: 'La flauta' },
		{ q: '¿Quién compuso la Novena Sinfonía?', a: 'Ludwig van Beethoven' },
		{ q: '¿En qué país surgió el reggae?', a: 'Jamaica' },
		{ q: '¿Cuántas cuerdas tiene una guitarra clásica?', a: 'Seis' },
		{ q: '¿Quién es conocido como el "Rey del Rock"?', a: 'Elvis Presley' },
		{ q: '¿Cuántas notas distintas tiene una escala mayor?', a: 'Siete' },
		{ q: '¿Qué banda cantaba "Bohemian Rhapsody"?', a: 'Queen (Freddie Mercury)' },
		{ q: '¿En qué país nació el tango?', a: 'Argentina' },
		{ q: '¿Qué nota sigue a Si en la escala musical?', a: 'Do' },
	],
	deportes: [
		{ q: '¿Cuántos puntos vale una canasta en baloncesto?', a: 'Dos o tres según la distancia' },
		{ q: '¿En qué deporte se usa una raqueta?', a: 'Tenis' },
		{ q: '¿Cuántos jugadores por equipo hay en la cancha de voleibol?', a: 'Seis' },
		{ q: '¿En qué deporte se juega con un volante?', a: 'Bádminton' },
		{ q: '¿En qué prueba atlética se lanza un disco?', a: 'Lanzamiento de disco' },
		{ q: '¿Cuántos carriles de competición tiene una piscina olímpica?', a: 'Ocho' },
		{ q: '¿En qué país se desarrolló el hockey sobre hielo moderno?', a: 'Canadá' },
		{ q: '¿Cuántos jugadores tiene un equipo de rugby union en el campo?', a: 'Quince' },
		{ q: '¿Cuál es la carrera más larga del atletismo olímpico?', a: 'Maratón (42,195 km)' },
		{ q: '¿En qué año se celebraron los primeros Juegos Olímpicos modernos?', a: '1896' },
	],
	peliculas: [
		{ q: '¿Cuántas películas componen la saga Skywalker de Star Wars?', a: 'Nueve' },
		{ q: '¿Quién dirigió "Titanic"?', a: 'James Cameron' },
		{ q: '¿En qué año se estrenó "Jaws" ("Tiburón")?', a: '1975' },
		{ q: '¿Cuál es la película de mayor taquilla mundial sin ajustar por inflación?', a: 'Avatar (2009)' },
		{ q: '¿Quién protagoniza la saga "Piratas del Caribe"?', a: 'Johnny Depp' },
		{ q: '¿En qué año se estrenó "El Padrino"?', a: '1972' },
		{ q: '¿Cuántas películas hay en la trilogía de "Volver al Futuro"?', a: 'Tres' },
		{ q: '¿Quién dirigió "Inception"?', a: 'Christopher Nolan' },
		{ q: '¿En qué año se estrenó "Iron Man", la primera película del Universo Cinematográfico de Marvel?', a: '2008' },
		{ q: '¿Qué superhéroe de DC es conocido como el Hombre de Acero?', a: 'Superman' },
	],
	flora: [
		{ q: '¿Cuál es la flor individual más grande del mundo?', a: 'Rafflesia arnoldii' },
		{ q: '¿Cuántas especies de plantas se conocen aproximadamente?', a: 'Alrededor de 400.000' },
		{ q: '¿Cuál es el árbol más alto del mundo?', a: 'La secuoya roja' },
		{ q: '¿En qué país vive el panda gigante?', a: 'China' },
		{ q: '¿Cuál es el animal más rápido del mundo en picada?', a: 'Halcón peregrino' },
		{ q: '¿Cuántas patas tiene un insecto?', a: 'Seis' },
		{ q: '¿Cuál es el animal terrestre más grande?', a: 'Elefante africano' },
		{ q: '¿Cuántas especies de primates existen aproximadamente?', a: 'Alrededor de 500' },
		{ q: '¿En qué continente vive la mayoría de los canguros?', a: 'Oceanía (Australia)' },
		{ q: '¿Cuál es el ave no voladora más grande?', a: 'Avestruz' },
	],
	arte: [
		{ q: '¿Quién pintó "La noche estrellada"?', a: 'Vincent van Gogh' },
		{ q: '¿En qué movimiento artístico destacó Picasso?', a: 'Cubismo' },
		{ q: '¿Quién esculpió "El Pensador"?', a: 'Auguste Rodin' },
		{ q: '¿En qué siglo se creó "Las Meninas"?', a: 'Siglo XVII (1656)' },
		{ q: '¿Sobre qué superficie se aplica la técnica del fresco?', a: 'Sobre yeso húmedo' },
		{ q: '¿Qué pintor italiano es conocido por sus frescos en la Capilla Scrovegni?', a: 'Giotto' },
		{ q: '¿En qué museo se encuentra "La Persistencia de la Memoria"?', a: 'Museo de Arte Moderno de Nueva York (MoMA)' },
		{ q: '¿Cómo se llama el arte realizado por humanos prehistóricos en cuevas?', a: 'Arte rupestre' },
		{ q: '¿Quién pintó "La joven de la perla"?', a: 'Johannes Vermeer' },
		{ q: '¿En qué año nació Leonardo da Vinci?', a: '1452' },
	],
};

export const CATEGORIES: { key: Category; label: string; emoji: string }[] = [
	{ key: 'general', label: 'Conocimiento General', emoji: '🧠' },
	{ key: 'historia', label: 'Historia', emoji: '📚' },
	{ key: 'futbol', label: 'Fútbol', emoji: '⚽' },
	{ key: 'musica', label: 'Música', emoji: '🎵' },
	{ key: 'deportes', label: 'Deportes', emoji: '🏆' },
	{ key: 'peliculas', label: 'Películas y Series', emoji: '🎬' },
	{ key: 'flora', label: 'Flora y Fauna', emoji: '🦁' },
	{ key: 'arte', label: 'Arte', emoji: '🎨' },
];
